### ISSUE TITLE
review await# generators - fixed plural singular, roadmap

### ISSUE THREAD

**Issue by mibamur** [opal/opal-rails#85]
Hello!
## plural bug - fixed here

controller_class_name
- https://github.com/opal/opal-rails/blob/master/lib/rails/generators/opal/assets/templates/javascript.js.rb#L15

controller_name
- https://github.com/opal/opal-rails/blob/master/lib/rails/generators/opal/assets/assets_generator.rb#L18

`rails g controller home index`

``` rb
#app/assets/javascripts/homes_view.js.rb
Class HomesView
```

I tried to find it ...

**Comment by mibamur** [comment]
## All done

So http://pastebin.com/zqb4jTiY

```rb
require 'rails/generators/named_base'

module Opal
  module Generators
    class AssetsGenerator < ::Rails::Generators::NamedBase
      def copy_opal
        template 'javascript.js.rb', File.join('app/assets/javascripts', class_path, "#{file_name}.js.rb")
      end
    end
  end
end
```

and we should use `class_name` instead `controller_class_name`

**Comment by mibamur** [comment]
ping @elia @meh @vais @Mogztter

I`d test it
rails 5.0
ruby 2.3.1

README.md should have something about generators
I do it all later

**Comment by mibamur** [comment]
# Roadmap

## opal-rails generators? For what?

- [x] author features? ( Tell him: Thanks a lot! ) @elia @meh @vais @Mogztter

- [x] Turbolinks
```rb
Document.on 'turbolinks:load' do |evt|
  puts "turbolinks:load #{evt}"
end
```
Could someone add it to README?

- [ ] rename `opal-rails/lib/rails/generators/opal/assets/assets_generator.rb`
maybe we can move opal to another assets folder and named it `opal`, rename opal_generator.rb

- [ ] Controller specific `ClassView` and method like `say_hello_when_a_link_is_clicked` 
Auto binding -> define `controller_name`, `action_name` in `id`, `class` or `data-attr` 
haml example
```haml
  %body{ class: "#{controller_name} #{action_name}", "data-controller-name"=>"#{controller_name}" }
```
Something else here? Sockets? I do not have idea now

- [ ] scaffold run -> add  index.js.rb create.js.rb delete.js.rb
- [ ] Split Sprockets -> make possible use Sprockets4 (ES5) and Opal (maybe as standalone compiler-builder)

**Comment by Mogztter** [comment]
@mibamur Hello, are you waiting something from me ?

**Comment by mibamur** [comment]
@Mogztter what should `ClassView` do? General idea is bind to action or anything, like `controller.coffee`?

**Comment by elia** [comment]
@mibamur sorry for the delay, I was quite busy in july and your PRs went off the radar.

I merged everything so far, thank you!

I like very much:

- adding generators that work with the rails scaffold command
- adding an initializer after bundle install

PRs for those would be very appreciated 😄.

As of sprockets4, support for it is under development. Sprockets support has been extracted to opal-sprockets to allow for independent upgrades.

**Comment by elia** [comment]
@mibamur is this still a work in progress or should I close the issue?

**Comment by elia** [comment]
Closing, let me know if you need to reopen this
